name: Changelog
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  changelog:
    name: Required Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
           changelog/*.md
      - run: exit 1
        if: ! env.GIT_DIFF
      - run: exit 0

