name: Changelog
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  changelog:
    name: Required Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
           changelog/*.md
      - name: Success
        if: env.GIT_DIFF
        run: exit 0
      - name: Failure
        run: exit 1

