on: pull_request
name: Require Changelog
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
           changelog/*.md
        run: exit 1
        if: ! env.GIT_DIFF
